const SUPABASE_URL = "https://kuzxbnlxjglolqgqdxxl.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1enhibmx4amdsb2xxZ3FkeHhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU5MDkyMDMsImV4cCI6MjA5MTQ4NTIwM30.OdsU50_49Hn1bwDMpAa-qu0UWqGXPsY1_nJF0hxQLYM";

const supabaseClient = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);